version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      -  pg-data:/var/lib/postgresql/data

  auth:
    build: ..
    container_name: authservice
    image: authservice
    environment:
      USER_TRANSPORT_URL: 'http://userservice:8080'
      USER_GRPC_URL: 'userservice:9091'
    ports:
      - 8082:8082

  user:
    build: ..
    container_name: userservice
    image: userservice
    environment:
      PG_URL: 'postgres://postgres:password@postgres/postgres'
      USER_GRPC_URL: 'userservice:9091'
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  pg-data:
