apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
spec:
  replicas: 1 # Number of replicas (pods) to run
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: daniarrr/authservice
          livenessProbe:
            httpGet:
              port: 8080
              path: "/healthz"
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 5
          ports:
            - containerPort: 8082
          env:
            - name: USER_TRANSPORT_URL
              value: '10.244.0.24:8080'
            - name: USER_GRPC_URL
              value: '10.244.0.24:9091'


---

apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  selector:
    app: authservice
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP

