apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: daniarrr/userservice
          livenessProbe:
            httpGet:
              path: "/healthz"
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 5
          ports:
            - containerPort: 8080
          env:
            - name: PG_URL
              value: 'postgres://postgres:password@10.105.201.138/postgres'

---

apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  selector:
    app: userservice
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
