apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: daniarrr/userservice # Replace with your actual image name
          ports:
            - containerPort: 8080
          env:
            - name: PG_URL
              value: 'postgres://postgres:password@192.168.49.2/postgres'
            - name: USER_GRPC_URL
              value: 'user:9091'

---

apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  selector:
    app: userservice
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
